/*
  Copyright 2020 ConserveIt, All Rights Reserved.
 */
apply plugin: 'java'
apply plugin: 'com.tridium.niagara'
apply plugin: 'com.tridium.niagara-module'


repositories {
  flatDir {
    name = "External JARs"
    dirs "${rootProject.ext.niagara_home}/bin/ext"
  }
  flatDir {
    name = "Nigara Modules"
    dirs "${rootProject.ext.niagara_home}/modules"
  }
  mavenCentral()
}

dependencies {
  moduleTestImplementation "Tridium:test-wb:4.0.0"
}

test {
  useTestNG()
}


javadoc.configure {
  failOnError false
  options.tags 'creation:a:Creation:'
  // Include or exclude specific package paths using the following syntax as an example
  include 'com/examples/**'
  exclude 'com/proprietary/**'
}

