//  Copyright (c) 2012, J2 Innovations
//  Licensed under the Academic Free License version 3.0
//
//  History:
//    10 Mar 2016  Richard McElhinney  Creation
//    26 Sep 2018  Andrew Saunders     Added dependency on tagdictionary to support Niagara
//                                     Haystack tags
//

description = "nhaystack workbench module"

moduleManifest {
    preferredSymbol = "nh"
    runtimeProfile = "wb"
    moduleName = "nhaystack"
}

dependencies {
    implementation "Tridium:nre:4.4.93.40"
    implementation "Tridium:baja:4.4.93.40"
    implementation "Tridium:alarm-rt:4.4.93.40"
    implementation "Tridium:driver-rt:4.4.93.40"
    implementation "Tridium:gx-rt:4.4.93.40"
    implementation "Tridium:control-rt:4.4.93.40"
    implementation "Tridium:driver-wb:4.4.93.40"
    implementation "Tridium:basicDriver-rt:4.4.93.40"
    implementation "Tridium:workbench-wb:4.4.93.40"
    implementation "Tridium:bajaui-wb:4.4.93.40"
    implementation "Tridium:gx-wb:4.4.93.40"
    implementation "Tridium:fox-rt:4.4.93.40"
    implementation "Tridium:history-rt:4.4.93.40"
    implementation "Tridium:schedule-rt:4.4.93.40"
    implementation "Tridium:tagdictionary-rt:4.4.93.40"

    implementation project(":nhaystack-rt")
}
